<?php
// $Id: elfinder.module 102 2011-02-20 20:11:52Z ph0enix $

/**
 * BUEditor support for elFinder
 * Copyright (c) 2011, Alexey Sukhotin
 */

function elfinder_elfinder_js_settings($settings) {
    if (preg_match('/(bueditor|bue)/', $settings['editorApp'])) {
      drupal_add_js(drupal_get_path('module', 'elfinder') . '/editors/bueditor/bueditor.callback.js');
      $settings['editorCallback'] = 'elfinder_bue_callback';
      
    }
  return $settings;
}

/* D7 Support */
function elfinder_element_info_alter(&$types) {
 elfinder_elements();
}

/* BUEditor settings hack */
function elfinder_elements() {
  $settings = array();
  $settings['BUE']['imceURL'] = url('elfinder', array('query' => array('app' => 'bueditor' ))); 
  drupal_add_js($settings, 'setting');
}
